## Исключительные ситуации (ошибки и исключения)

Исключения в Java — это важный аспект программирования, обеспечивающий обработку ошибок и других нештатных (исключительных) ситуаций в программе.

В иерархии исключений Java класс `Throwable` является корневым для всех ошибок и исключений. От него наследуются два основных подкласса:

- **`Exception`**: Этот класс представляет все проверяемые исключения, которые должны быть обработаны в программе. `Exception` далее делится на:
    - **Проверяемые исключения (Checked Exceptions)**: Например, `IOException`, `SQLException`.
    - **Непроверяемые исключения (Unchecked Exceptions)**: Эти исключения наследуются от `RuntimeException`, например, `ArithmeticException`, `NullPointerException`.

- **`Error`**: Этот класс представляет серьёзные ошибки, которые обычно связаны с работой виртуальной машины Java, и их не предполагается обрабатывать в обычных приложениях. Примеры включают `OutOfMemoryError`, `StackOverflowError`.

<img src="https://raw.githubusercontent.com/ait-tr/cohort42.1/main/basic_programming/lesson_43/img/Exeptions.jpeg" width="100%">


В Java исключения делятся на две основные категории:

1. **Проверяемые исключения (Checked Exceptions)**: Эти исключения должны быть явно обработаны в программе. Компилятор Java проверяет, правильно ли обработаны эти исключения, и если нет, он выдаёт ошибку компиляции. Примеры включают `IOException`, `SQLException`.

2. **Непроверяемые исключения (Unchecked Exceptions)**: Эти исключения не требуют явной обработки. Они в основном указывают на ошибки в программе, такие как деление на ноль (`ArithmeticException`) или обращение к элементу за пределами массива (`ArrayIndexOutOfBoundsException`). Непроверяемые исключения наследуются от `RuntimeException`.

Всего в Java классов-исключений почти 400! Зачем так много? Именно для того, чтобы программистам было удобнее с ними работать.

Проверяемые исключения (checked exceptions) — это тип исключений, наличие которых вы обязаны проверить в своём коде и обработать их.
В Java компилятор требует, чтобы все методы, которые могут выбросить проверяемое исключение, либо обрабатывали это исключение с помощью блока `try-catch`, либо объявляли это исключение в своей сигнатуре с помощью ключевого слова `throws`.

Пример с `FileNotFoundException`:

```
public class CheckedExceptionExample {
    public void readFile(String filePath) throws FileNotFoundException {
        FileReader file = new FileReader(filePath); // FileReader выбрасывает FileNotFoundException
    }
    
    public static void main(String[] args) {
        CheckedExceptionExample example = new CheckedExceptionExample();
        try {
            example.readFile("somefile.txt");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
```

В примере выше, метод `readFile` объявляет, что он может выбросить `FileNotFoundException`, которое является проверяемым исключением. Это означает, что любой код, вызывающий `readFile`, должен либо обработать это исключение (использовать `try-catch`), либо также объявить `throws FileNotFoundException` в своей сигнатуре.

### Обработка исключений

Обработка исключений в Java включает в себя несколько ключевых концепций и конструкций:

- **try-catch**: Блок `try` используется для оборачивания кода, который может вызвать исключение, а `catch` для перехвата и обработки исключения.

```
try {
    // код, который может вызвать исключение
} catch (ExceptionType name) {
    // код для обработки исключения
}
```

- **finally**: Блок `finally` используется для кода, который должен выполниться независимо от того, было ли исключение перехвачено.

```
try {
    // код, который может вызвать исключение
} catch (ExceptionType name) {
    // код для обработки исключения
} finally {
    // код, который выполнится в любом случае
}
```

- **throws**: Ключевое слово `throws` используется в сигнатуре метода для указания, что метод может выбросить исключение.

```
public void myMethod() throws ExceptionType {
    // если здесь произойдет исключение, оно будет выброшено
}
```

- **throw**: Ключевое слово `throw` используется для явного выброса исключения.

```
public void myMethod() {
    if (someCondition) {
        throw new ExceptionType("Сообщение об ошибке");
    }
}
```

### Создание собственных исключений

Вы можете создать свой класс исключений, наследуя от класса `Exception` (для проверяемых) или `RuntimeException` (для непроверяемых).

```
public class MyException extends Exception {
    public MyException(String message) {
        super(message);
    }
}
```

**Переопределение методов при наследовании от `RuntimeException`**:

Когда вы наследуетесь от `RuntimeException`, вы можете переопределить несколько методов, чтобы обеспечить более детальную информацию об исключении, например:

- `getMessage()`: Возвращает строку с описанием исключения.
- `getCause()`: Возвращает исключение, которое вызвало текущее исключение.
- `toString()`: Возвращает строковое представление объекта исключения.
- `printStackTrace()`: Выводит трассировку стека исключения.

```
public class MyRuntimeException extends RuntimeException {
    public MyRuntimeException(String message) {
        super(message);
    }

    @Override
    public String getMessage() {
        return "Дополнительное сообщение: " + super.getMessage();
    }

    // Другие методы можно переопределить по необходимости
}
```

Каждый из этих методов может быть переопределен для предоставления специализированной информации о вашем исключении. Однако стоит отметить, что переопределение методов `RuntimeException` не обязательно; это делается только для добавления функциональности или информации к вашему собственному исключению.
